name: B1
run-name: "Build a release from: -> ${{ github.workflow }} (on tag: @${{ github.ref_name }})"

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  # Allows you to run this workflow manually from the Actions tab (for testing)
  workflow_dispatch:


jobs:

  setup:
    name: "Validate version"
    runs-on: ubuntu-latest

    outputs:
      formatter_server_ref: ${{ steps.validated.outputs.FORMATTER_SERVER_REF }}

    steps:
      - run: |
          FORMATTER_SERVER_REF="aver"
          echo "FORMATTER_SERVER_REF=$FORMATTER_SERVER_REF" >> $GITHUB_OUTPUT

  build1:
    needs: setup
    if: needs.setup.result == 'success'

    uses: tekert/test-gh-actions1/.github/workflows/build.yml@{{needs.setup.outputs.formatter_server_ref}}
#    with:
#      target: "--last-release"
    secrets: inherit

  build2:
    needs: [build1]
    if: needs.build1.result == 'success'
    runs-on:  ubuntu-latest

    steps:

      - name: Set github envs for debug
        run: echo 'Set github envs for debug' #'${{ toJSON(needs) }}'
        env:
          GITHUB_JSON: ${{ toJSON(github) }}
          NEEDS_JSON: ${{ toJSON(needs) }}
          ENV_JSON: ${{ toJSON(env) }}
          INPUTS_JSON: ${{ toJSON(inputs) }}
        working-directory: "."

      - name: Display structure of downloaded files
        run: ls -R

      # Download artifact
      - name: "Download build artifacts"
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: "Checkout local repository"
        uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        with:
          name: test
          path: README.md
