name: test1
run-name: "Build a release from: -> ${{ github.workflow }} (on tag: @${{ github.ref_name }})"

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  # Allows you to run this workflow manually from the Actions tab (for testing)
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:

    runs-on:  ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # https://github.com/actions/checkout
      - name: "Checkout local repository"
        uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        with:
          name: test
          path: README.md
