name: B1
run-name: "Build a release from: -> ${{ github.workflow }} (on tag: @${{ github.ref_name }})"

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  # Allows you to run this workflow manually from the Actions tab (for testing)
  workflow_dispatch:


jobs:

  build:
    uses: tekert/test-gh-actions1/.github/workflows/build.yml@master
    with:
      target: "--last-release"
    secrets: inherit

  build1:

    runs-on:  ubuntu-latest

    steps:
      - name: Display structure of downloaded files
        run: ls -R

      # Download artifact
      - name: "Download build artifacts"
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: "Checkout local repository"
        uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        with:
          name: test
          path: README.md
