name: test
run-name: "TEST"

on:
  workflow_dispatch:


jobs:

  test:

    runs-on:  ubuntu-latest

    steps:

      - name: Set github envs for debug
        run: |
          echo "::warning::Package v$PACKAGE_VERSION and tag $BUILD_REF_TAG version mismatch"
        env:
          GITHUB_JSON: ${{ toJSON(github) }}
          NEEDS_JSON: ${{ toJSON(needs) }}
          ENV_JSON: ${{ toJSON(env) }}
          INPUTS_JSON: ${{ toJSON(inputs) }}
        working-directory: "."
